name: flutter_app_router_example
description: 示例怎么使用AppRouter库
# 添加版本号配置
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # 依赖父级目录的包（使用 path）
  flutter_app_router:
    path: ../

  # 其他依赖（如果是 Flutter 项目）
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.0
  webview_flutter_wkwebview: ^3.9.0
  url_launcher: ^6.2.3
  uri: ^1.0.0
  collection: ^1.17.0 # 版本号可根据实际情况调整
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

